@Extension.WebAPI_HostAddress = http://localhost:5167

Get {{Extension.WebAPI_HostAddress}}/api/authorization/get?url=https%253A%252F%252Fstackoverflow.com%252F
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InRvbSIsIm5iZiI6MTczODY4ODA1MiwiZXhwIjoxNzM4NzAyNDUyLCJpYXQiOjE3Mzg2ODgwNTIsImlzcyI6ImxvY2FsaG9zdCIsImF1ZCI6ImV4dGVuc2lvbiJ9.Tuwjq2lcpMYkv06TyKeNL9JchGgqP0Nfa4mthqdkGVI




###
GET {{Extension.WebAPI_HostAddress}}/api/login/get
Authorization: Basic JXNhWSZzQGZnayphc2QhMjRG