@Extension.WebAPI_HostAddress = http://localhost:5167

Get {{Extension.WebAPI_HostAddress}}/api/authorization/get?url=http://discord.com





###
GET {{Extension.WebAPI_HostAddress}}/api/login/tom
Authorization: Basic JXNheSZzQGZnayphc2QhMjRG